### ISSUE TITLE
1:00 Min timeout timer - Time is 10 instead of 60 in source code

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#1]
function startTimeoutTimer() {
        timeoutStartTime = new Date().getTime();
        timerInterval = setInterval(() => {
            let passedSec = Number.parseInt((new Date().getTime() - timeoutStartTime) / 1000);
            let restSec = TIMEOUT_TIME_SEC - passedSec;
            if (config.devTimeMode && gameTime == 60) {
                restSec = 10 - passedSec;				**// must be 60 instead of 10 seconds**
            }

            if (restSec <= 0) {
                clearInterval(timerInterval);
                timeoutStartTime = -1;
                updateTimeoutTimer(-1);
                makeAlert(true, 1000, 1);
            } else {
                updateTimeoutTimer(restSec);
            }
        }, 1000);
    }

**Comment by msaltnet** [comment]
v1.2.1
