### ISSUE TITLE
[BUG] Auto Start Break-Timer is not working

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#12]
After the first half-time the 10 Min break timer should start automatically and stop after the 10 Min. 
It should not be possible to interrupt this timer.

Reason:
The real 10 Min break for the player starts directly after the first half-time. 
If the break-timer is interrupted by accident by the user it cant be fast-forward to stay in the real 10 min frame. 
But the game must go on after the 10 min. 
Worst case: the referee could not use the timer for the second half-time.

**Comment by msaltnet** [comment]
>After the first half-time the 10 Min break timer should start automatically and stop after the 10 Min.
It should not be possible to interrupt this timer.

V1.2.2

**Comment by SMD2023** [comment]
Auto Start and countdown works perfect
