### ISSUE TITLE
[FEATURE] - editing maintime

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#13]
During our live test we get in trouble with time keeping. 
If the referee forget to continue or stop the time while the official clock do, it is very difficult to syncronize the time.

It would be perfect if we can add a "change main timer" Button in setting.

**Comment by msaltnet** [comment]
I am sorry. I don't want to move another version with bew features.

It is already too far from the our first plan.

If you want, you can make it yourself.

https://docs.tizen.org/application/web/index

**Comment by SMD2023** [comment]
ok
