### ISSUE TITLE
[BUG] - Halfe-Time Counter in backend seems to be damaged

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#14]
Start team icon is fix now and don't change. 
I think there is a general proble with "naming the half-time" 
because
it is possible to go on and on and on with the half-times. 

How I tested it:
- run 40 Min game 
   - First half-time time OK
   - break OK
   - second half-time OK
   BUT then I can continue with a break and another half-time and so on... 
There was no freeze at the end. 

This is the reason why I could imagine that there is the counter for half-time is missing in backend.

**Comment by SMD2023** [comment]
Additional information: 
When I am in pause and click on "new game" I am still in "pause-mode". with the yellow circle.

**Comment by msaltnet** [comment]
I don't understand a problem.

run 40 Min game
First half-time time OK // 20 min 
break OK // 10 min
second half-time OK // 20 min ->  went to game over state.
BUT then I can continue with a break and another half-time and so on... // ?? is it possible continue after finish game??
There was no freeze at the end.

 is it possible continue after finish game(second half finished)?

**Comment by SMD2023** [comment]
It seems to work now. Don't know why there was a problem. If I see it again, I will report.
