### ISSUE TITLE
[FEATURE] 1:00 Min Timeout Timer with circle

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#15]
lets try this easier code. It worked in a privious code. Its only neccessary to adapt it to the actual colored circle. 
Maybe 
during timeout:
the greycircle could overlay the actual colored circle and the moving yellow break circle is on top of all.  

** >>>>> JAVASCRIPT <<<<<**
/**
* The setTimeout({},0) is a workaround for what appears to be a bug in StackSnippets.
* It should not be required. See JSFiddle version.

SOURCE: https://stackoverflow.com/questions/29649643/how-to-create-a-circular-countdown-timer-using-html-css-or-javascript
*/

function setTimeoutTimer() { 

  var time = -60; /* how long the timer will run (seconds) */   /* Time -60 instead of 60 and it flow clockwise */
  var initialOffset = '1068';  /*segments of the circle */
  var i = 1

  /* Need initial run as interval hasn't yet occured... */
  $('.circle_animation').css('stroke-dashoffset', initialOffset-(1*(initialOffset/time)));

  var interval = setInterval(function() {
      $('h5').text(i);
      if (i == 60) {                   /* INTERVAL FIX TO 60 SECONDS */
        clearInterval(interval);      /* IMPORTANT: WE NEED AN INTERRUPTION HERE TO CONTINUE MAIN-TIMER*/
        return;
      }
      $('.circle_animation').css('stroke-dashoffset', initialOffset-((i+1)*(initialOffset/time)));
      i++;  
  }, 1000);

}

** >>>>> HTML <<<<<**
       <div id="timeouttimer" class="main-box">
		
			<svg id="greycircle" height="360" width="360">
			<circle r="170" cy="180" cx="180" stroke-width="16" stroke="#1d2327" fill="none"  z-index="1" />
			</svg>
			
			<svg width="360" height="360" xmlns="http://www.w3.org/2000/svg">
			  <circle id="circle" class="circle_animation" r="170" cy="180" cx="180" stroke-width="16" stroke="#ffff00" fill="none" stroke-linecap="round"/>
			</svg>
	</div>

** >>>>> CSS <<<<<<**
/* NEW BREAKOUT TIMER */
#breakouttimer {
	position: absolute;
	text-align: center;
	font-size: 36px;
	width: 200px;
	height: 125px;
	left: 80px;
	bottom: 3px;
	color: grey;
	z-index: 2;
}

.item {
    position: relative;
    float: left;
}

#h5 {
    position: absolute;	
}

svg {
   -webkit-transform: rotate(-90deg);
    transform: rotate(-90deg);
	position: absolute;
	top: 0px;
}

.circle_animation {
  stroke-dasharray: 1068; /* this value is the pixel circumference of the circle */
  stroke-dashoffset: 1068;
  transition: all 1s linear;
}

.greycircle {
	position: absolute;
	top: 0px;
}

**Comment by SMD2023** [comment]
Example for starting timeout timer in maintimer: 

`
    function toggleStopwatch() {
        console.log(`Previous mode: ${modeStopwatch}`);
        if (isFinished) {
            console.log('Game is finished! - toggleStopwatch is ignored');
            return;
        }
        switch (modeStopwatch) {
            case "Pause":
                // Pause -> Start
                modeStopwatch = "Start";
                interruptTimoutTimer = true;
                if (animRequest == 0)
                    animRequest = window.requestAnimationFrame(drawStopwatchAnimationFrame);
                break;

            case "Start":
                // Start -> Pause
                modeStopwatch = "Pause";
                timePrevFrame = 0;
                window.cancelAnimationFrame(animRequest);
                animRequest = 0;
				interruptTimoutTimer = false;
                setTimeoutTimer();						//START 1 MIN TIMEOUTTIMER
                break;
            default:
                break;
        }
    }
`

**Comment by msaltnet** [comment]
I am sorry. I don't want to move another version with bew features.

It is already too far from the our first plan.

If you want, you can make it yourself.

https://docs.tizen.org/application/web/index

**Comment by SMD2023** [comment]
thats okey, we only need to fix the 1:00 timer issue. I will raise a case for that extra :)
