### ISSUE TITLE
[BUG] 1:00 timeout timer can not be interrupted 

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#16]
Behaviour: 
I tested the 1:00 timeout timer accidently. Regularly I use the button to start stop and nothing happens with the timeout timer. 
After stopping the time accidently on the display I recognized that the 1:00 timer is counting down. 
I continued the main timer with the main button. The  1:00 timout timer is still counting down and beeps at the end. 

Bugs:
- 1:00 timeout timer only starts by stopping the main-timer via touch not via button.
- 1:00 timeout timer cant be interrupted by touch or button
- during 1:00 timeout the maintimer can continue only by button not by touch     
            after clicking the button the timeout timer is still running instead of setting back to 1:00. 
            (therefore 2 or 3 timeouts are not possible in one minute - but should be).

Need to fix:
=> timeout timer should start via button, too. 
=> continue main timer should be possible via touch, too  even during 1:00 timer is running
=> when continue the main-timer the timeout timer stops and set back to 1:00 => It is possible to start it directly again after continue the game.

**Comment by msaltnet** [comment]
v1.3.0
- timeout timer should start via button, too.
  - done
- continue main timer should be possible via touch, too even during 1:00 timer is running
  -  done
- when continue the main-timer the timeout timer stops and set back to 1:00 => It is possible to start it directly again after continue the game.
  - done
