### ISSUE TITLE
Change circle colour to yellow while 1:00 timeout timer

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#19]
Is it possible to change the color of the circle to "yellow" while the main timer is stopped?

So the user will see really qick when he forgot to start the time again because the circle is not green.

**Comment by msaltnet** [comment]
You mean you want the color of the circle to change during timeout?
Sure, what color do you want?
v1.4.0, color is out during timeout.

**Comment by SMD2023** [comment]
Your solution fits great!
