### ISSUE TITLE
In touch mode back button ends app. 

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#23]
Regularly we use the button mode. 
If someone uses the touch mode and klick the back button, the app will be closed. 
Closing the app means lossing the game information => new game would be startet by restarting the app. 
If it can be fixxed, would be great. If not -> maybe delete button/touch option in settings and only use button :)

**Comment by msaltnet** [comment]
The back button behavior has been changed to hide instead of exit. It mean that app is not terminated and user re-start app without loss game information.
V1.4.0
