### ISSUE TITLE
green circle problem with 1:00 timeout timer

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#25]
Regularly the green circle works perfect. 
Main Timer is running = green    
stop = gray

BUT

After the 1:00 is running to 0:00 the timer is waiting. That is totally correct. 

If I start the time again (AFTER 1:00 is counted down to 0:00) the circle does not change the color to green. 
If I stop the main timer again and start the main timer while the timeout timer is counting down the color is switching to green. 

So the problem ONLY is visible AFTER counting down to 0:00 and waiting to continue.

**Comment by msaltnet** [comment]
I got it.

**Comment by msaltnet** [comment]
v1.5.0

**Comment by SMD2023** [comment]
Great :) I will see in next uploaded version
