### ISSUE TITLE
Store description

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#27]
I am not sure if you get the Email.

For samsung store I wrote a description in english and german and added a screenshot of the app screen. If you want you can use it :)

Description idea for app store ENGLISH
The app supports you in your tasks as a handball referee in time keeping and goal tracking.
It's an easy to use, intuitive and stand-anlone app. No extra software is needed.
Special feature: Start / stop via button and touch makes timetracking easy.

Features
- Start/stop game timer via button and touch.
- Variable Game time (40, 50 or 60-minutes).
- 1:00 minute timeout timer with color changing circle and vibration reminder to continue the main timer.
- Automatic starting 10:00 minutes break countdown.
- Vibration alert 30 seconds before end of each halfe-time.
- Goal counter for guest and home team (short press +1, long press -1).
- Color selection for guest and home team for easy goal tracking.
- Selection of start team (team switches after break to show start team for 2nd halfe-time).
- Continue timer in second halfe-time or restart to sync with scoreboard.

Description idea for app store GERMAN
Die App unterstützt Sie bei Ihren Aufgaben als Handball-Schiedsrichter bei der Zeitmessung und dem Zählen der Tore.
Es ist eine einfach zu bedienende, intuitive und eigenständige App. Es wird keine zusätzliche Software benötigt.
Besondere Funktion: Start/Stop per Button und Touch macht die Zeitmessung einfach.

Funktionen
- Start/Stopp der Spielzeit per Taste und Berührung.
- Variable Spielzeit (40, 50 oder 60 Minuten).
- 1:00 Minuten Timeout-Timer mit farbwechselndem Rand und Vibrationserinnerung zur Fortsetzung des Haupttimers.
- Automatisch startender 10:00 Minuten Countdown für die Pause.
- Vibrationsalarm 30 Sekunden vor Ende jeder Halbzeit.
- Torzähler für Gast- und Heimmannschaft (kurzes Drücken +1, langes Drücken -1).
- Farbauswahl für Gast und Heim zur einfachen Torverfolgung.
- Auswahl der Startmannschaft (Startteam nach der Pause wird angezeigt).
- Fortsetzung des Timers in der zweiten Halbzeit oder Neustart der Zeit zur Synchronisierung mit der Anzeigetafel.

You could use this picture for preview in app store :)
![Screen_20230304_225528](https://user-images.githubusercontent.com/124830764/223154532-da64ef73-f694-4b89-9eba-9200a7acad47.png)

**Comment by msaltnet** [comment]
Thanks! :)

**Comment by SMD2023** [comment]
You are welcome.  We have to thank you very much.
