### ISSUE TITLE
All tested game times behave like a 40 Min game - I WILL CONFIRM TOMORROW

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#4]
regardless of which game time is set, the pre-alarm is triggered at 19:30 Min. 
After 20:00 Min the clock pauses and waits for the half-time break / the start of the second half.  This is correct behavior for 40 Min game but not for 50 or 60 min game.

**Comment by msaltnet** [comment]
You mean that pre-alarm time is not correct when 50 min game?

**Comment by SMD2023** [comment]
40 Min game is perfect
50 Min game is perfect
60 Min game is still developement
