### ISSUE TITLE
PRE-ALARM is working correct, 10 Min Break Timer need to be a countdown timer

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#5]
I verified for 40 Min game: 

Manual START - 1st half
19:30 - pre-alert
20:00 - finish first half
auto STOP

Manual START - 10 Min BREAK   
10:00 - finish break
auto STOP

Manuarl START - 2nd half
19:30 - pre-alert
20:00 - finish second half
auto STOP

Pre-Alarm for 40 min game is working correct. 

Tomorrow I will test 50 min and 60 min Games again

**Comment by SMD2023** [comment]
I am not sure and need to verify if you created the actual game like this:

Manual START - 1st half
19:30 - pre-alert
20:00 - finish first half
auto STOP

Manual START - 10 Min BREAK
10:00 - finish break
auto STOP

Manuarl START - 2nd half
19:30 - pre-alert
20:00 - finish second half
auto STOP

**Comment by SMD2023** [comment]
If it is like described:
Because the Break Time is counting up and not a 10:00 to 0:00 countdown I can't determine that it was the break time. 

Maybe this was planned in a further version.

**Comment by SMD2023** [comment]
I cant decide between gametime and Break time. Therefor I thought there was an error. 
We need to change the Breakout timer from upcounting 00:00 - 10:00 to countdown 10:00 - 00:00

**Comment by msaltnet** [comment]
How about change color of circle?
green - red (after pre-alert) - orange(break time) - green - red

**Comment by SMD2023** [comment]
Count down would be perfect. 
Yellow Circle would be okey, too. 
Then lets do the circle thing afterwartds. 
**Maybe you can change the font color to yellow during the break? and before and after that white?**

**Comment by msaltnet** [comment]
> Maybe you can change the font color to yellow during the break? and before and after that white?

Sure, I will try to change font and circle color soo.

**Comment by msaltnet** [comment]
v1.2.2

**Comment by SMD2023** [comment]
Its working perfect.
Please set circle color to yellow or #FFFF00
