### ISSUE TITLE
Vibration time 

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#6]
**ACTUAL**
 alarmList.push({
            time: gameTimeSec - preAlarmSec,
            soundDurationMs: 0,
            vibrationCount: 1,
            needReset: false,
            needStop: false,
            isGameAlarm: true
        });
        alarmList.push({
            time: gameTimeSec,
            soundDurationMs: 1000,
            vibrationCount: 1,
            needReset: true,
            needStop: true,
            isGameAlarm: true
        });
        alarmList.push({
            time: halftimeBreakSec,
            soundDurationMs: 1000,
            vibrationCount: 1,
            needReset: true,
            needStop: true,
            isGameAlarm: false
        });
        alarmList.push({
            time: gameTimeSec - preAlarmSec,
            soundDurationMs: 0,
            vibrationCount: 1,
            needReset: false,
            needStop: false,
            isGameAlarm: true
        });
        alarmList.push({
            time: gameTimeSec,
            soundDurationMs: 1000,
            vibrationCount: 1,
            needReset: false,
            needStop: true,
            isGameAlarm: true
        });

**Comment by SMD2023** [comment]
**NEW**
        alarmList.push({
            time: gameTimeSec - preAlarmSec,
            soundDurationMs: 0,
            vibrationCount: 3,
            needReset: false,
            needStop: false,
            isGameAlarm: true
        });
        alarmList.push({
            time: gameTimeSec,
            soundDurationMs: 1000,
            vibrationCount: 5,
            needReset: true,
            needStop: true,
            isGameAlarm: true
        });
        alarmList.push({
            time: halftimeBreakSec,
            soundDurationMs: 1000,
            vibrationCount: 5,
            needReset: true,
            needStop: true,
            isGameAlarm: false
        });
        alarmList.push({
            time: gameTimeSec - preAlarmSec,
            soundDurationMs: 0,
            vibrationCount: 3,
            needReset: false,
            needStop: false,
            isGameAlarm: true
        });
        alarmList.push({
            time: gameTimeSec,
            soundDurationMs: 1000,
            vibrationCount: 5,
            needReset: false,
            needStop: true,
            isGameAlarm: true
        });

**Comment by msaltnet** [comment]
please check v1.2.1

**Comment by SMD2023** [comment]
Vibration is perfect but now sound is not working at the moment.
