### ISSUE TITLE
back / start/stop button leads to settings after game end

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#7]
If I click on start/stop button after end of game the app will switch to settings. 
If a user clicks accedently on this button the freezed information are lost. 

=> Only settings icon leads to settings 
No function for start/stop button after game-end. 

freezing the end time (in the testes case 20:00) is working correct :)

**Comment by msaltnet** [comment]
v1.2.3

**Comment by SMD2023** [comment]
Back Button is still going to settings instead of doing nothing at end of the game. 
Fyi: game Information is freezing and still there if I got to setting and back. This is great. 

=> Only settings icon leads to settings
No function for start/stop button after game-end.

**Comment by msaltnet** [comment]
Only settings icon leads to settings
No function for start/stop button after game-end

OK, I will be applied next version.

**Comment by msaltnet** [comment]
v1.3.0
