### ISSUE TITLE
[BUG] - Vibration is perfect but now the sound is not working - REVIEW ON MY SIDE

### ISSUE THREAD

**Issue by SMD2023** [msaltnet/handball-stopwatch#9]
doesnt matter which clock (tested on 2 devices). sound doesnt work if activated in options.

**Comment by msaltnet** [comment]
v1.2.2

**Comment by SMD2023** [comment]
Sound is still not working. Maybe it is combined with the half-time counter problem in backend.

**Comment by msaltnet** [comment]
The root cause was about the mismatch between sound setting default value and display settings value. I will check it again on v1.2.3. and update this ticket.

**Comment by SMD2023** [comment]
Tested again. Still no sound ...

**Comment by msaltnet** [comment]
What if you change sound settings
What if you Uninstaller app and re-install
Please check it again.
I will test again too.

**Comment by SMD2023** [comment]
I test 50 min game at the moment and started the 1:00 timeout timer. Sound is working there. after 1 Min there is a beep.

**Comment by SMD2023** [comment]
For 50 min game is okey. I will test it with 40 and 60 min game, too and write feedback.

**Comment by SMD2023** [comment]
Sound is working
